return {
  {'nvim-telescope/telescope.nvim', tag = '0.1.8', dependencies = {'nvim-lua/plenary.nvim'}},
  {'nvim-tree/nvim-tree.lua'},
  {'neovim/nvim-lspconfig'},
  {'nvim-treesitter/nvim-treesitter', build = ":TSUpdate"},
  {'ellisonleao/gruvbox.nvim'},
  {'nyoom-engineering/oxocarbon.nvim'},
  {'tanvirtin/monokai.nvim'},
  {'saghen/blink.cmp', dependencies = {'rafamadriz/friendly-snippets'}, version = '*', lazy = true},
  {'sschleemilch/slimline.nvim'},
  {'lewis6991/gitsigns.nvim'},
  {'nvimdev/lspsaga.nvim'},
  {'ThePrimeagen/harpoon', dependencies = {'nvim-lua/plenary.nvim'}},
  {'crusj/structrue-go.nvim', branch = 'main'},
  {'tris203/precognition.nvim'},
  {'sindrets/winshift.nvim'},
  {'windwp/nvim-autopairs', event = 'InsertEnter', config = true},
  {'windwp/nvim-ts-autotag', event = 'InsertEnter'},
  {'rmagatti/auto-session'},
  {'tadaa/vimade'},
  {'folke/which-key.nvim'},
  {'akinsho/bufferline.nvim', version = "*", dependencies = 'nvim-tree/nvim-web-devicons'},
  {'folke/todo-comments.nvim', dependencies = {'nvim-lua/plenary.nvim'}},
  {'samharju/yeet.nvim', dependencies = {'stevearc/dressing.nvim'}}
}
